on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 1.8
    - name: Test
      run: mvn test -Dtest=!ppd.PPDTest
    - name: PPDTest
      run: mvn test -Dtest=ppd.PPDTest
